---
on:
  push:
    branches:
      - master

name: Build and Publish
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup env
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
        name: Install dependencies
      - name: ESLint checks
        run: yarn lint
      - run: yarn build
        name: Compile Typescript
      - run: yarn test
        name: Run tests
      - name: Publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.node_github_token }}
          NPM_AUTH_TOKEN: ${{ secrets.npm_token }}
